name: Print Environment Variables
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch from which prints the environment'
        required: true
        default: 'main'



jobs:
  print-info:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [linux, windows, macos]
        arch: [x64, arm64]

    steps:
      - name: Print runner.os
        run: |
          echo "Runner OS: ${{ runner.os }}"

      - name: Print matrix.os and matrix.arch
        run: |
          echo "Matrix OS: ${{ matrix.os }}"
          echo "Matrix Target: ${{ matrix.target }}"
          echo "Matrix Arch: ${{ matrix.arch }}"

