name: Print Environment Variables
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch from which prints the environment'
        required: true
        default: 'main'



jobs:
  print-info:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]

    steps:

      - name: Print matrix.os and matrix.arch
        run: |
          echo "Matrix OS: ${{ matrix.os }}"
          echo "Runner: ${{ runner.os }} => ${{ runner.arch }}"
          echo "Matrix Arch: ${{ matrix.arch }}"

